---
- name: WEB2PY
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Run And Configure
      tags:
        - run
      include_tasks:
        file: jobs/build/{{ item }}.yml
        apply:
          tags:
            - build
      loop:
        - run
    - name: build
      tags:
        - build
      include_tasks:
        file: jobs/run/{{ item }}.yml
        apply:
          tags:
            - build
      loop:
        - build
    - name: Run tests to make sure app is running as expected
      tags:
        - test
        - run
      include_tasks:
        file: jobs/tests/{{tests.}}yml
          apply:
            tags:
              - run
      loop:
        - test