---
- name: WEB2PY
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: build
      tags:
        - build
      include_tasks:
        file: jobs/build/{{ item }}.yml
        apply:
          tags:
            - build
      loop:
        - build
